title: AllWize Wiki
author: AllWize
email: github@allwize.io
description: >
  A review of products and projects by AllWize.io

remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

plugins:
  - github-pages  